### PR TITLE
Update Runtime.php

### PR DESCRIPTION
**Pull request by frontendschlampe**
allow access for *.woff2 files

### CODE REVIEW

**Comment by discordier** [comment]
We do not have a Web font in the client.
What issue is this PR resolving?

**Comment by frontendschlampe** [comment]
It's solve the problem, that if you use e.g. components/font-awesome Google Chrome can use the *.woff2 font, which is within composer/vendor/components ... What's the Problem? Why you allow *.woff and the other files and not *.woff2?!

**Comment by frontendschlampe** [comment]
If you want to have a separate issue, I will create one, but I think it should be faster when I make a pr! :-P

**Comment by discordier** [comment]
No, thanks for clarification. I did not think about components.

**Comment by discordier** [comment]
Has been merged with 7d666f2cd328c874625eb0c9c7b67ae6f71c1970

**Pull request closed without merging**
